import { CardProps } from "@/types/card";

export const cardData: CardProps[] = [
  {
    id: 1,
    title: "How 7 lines code turned into $36 Billion Empire",
    category: "Business",
    date: "20 Sep 2022",
    status: "Published",
    views: 428,
    image: "/images/c1.jpg",
  },
  {
    id: 2,
    title: "Chez pierre restaurant in Monte Carlo by Vuidafieri",
    category: "Business",
    date: "20 Sep 2022",
    status: "Created",
    views: 438,
    image: "/images/c2.jpg",
  },
  {
    id: 3,
    title: "Teknion wins Gold at 2022 International Design Awards",
    category: "Politics",
    date: "20 Sep 2022",
    status: "Draft",
    views: 1628,
    image: "/images/c3.jpg",
  },
  {
    id: 4,
    title: "How 7 lines code turned into $36 Billion Empire",
    category: "Business",
    date: "20 Sep 2022",
    status: "Published",
    views: 158,
    image: "/images/c4.jpg",
  },
  {
    id: 5,
    title: "Tesla's secret AI lab leaked by former engineer",
    category: "Technology",
    date: "18 Oct 2022",
    status: "Published",
    views: 372,
    image: "/images/c3.jpg",
  },
  {
    id: 6,
    title: "A guide to building the ultimate remote workspace",
    category: "Design",
    date: "15 Oct 2022",
    status: "Draft",
    views: 210,
    image: "/images/c1.jpg",
  },
  {
    id: 7,
    title: "Inside Dubai’s futuristic museum of the future",
    category: "Travel",
    date: "12 Oct 2022",
    status: "Created",
    views: 529,
    image: "/images/c4.jpg",
  },
  {
    id: 8,
    title: "Elon Musk’s Neuralink gets FDA approval for human trials",
    category: "Science",
    date: "10 Oct 2022",
    status: "Published",
    views: 690,
    image: "/images/c1.jpg",
  },
  {
    id: 9,
    title: "How AI is revolutionizing the music industry",
    category: "Entertainment",
    date: "09 Oct 2022",
    status: "Created",
    views: 305,
    image: "/images/c2.jpg",
  },
  {
    id: 10,
    title: "The rise of minimalism in modern architecture",
    category: "Architecture",
    date: "05 Oct 2022",
    status: "Published",
    views: 413,
    image: "/images/c3.jpg",
  },
];
